name: Python application test

on: [push]

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

  test-application:
    runs-on: ubuntu-latest
    needs: check-python-version
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run Flask app
        run: |
          nohup python app.py &
          sleep 5  # gives Flask time to start
      - name: Check if Flask app is up and displays the correct message
        run: |
          response=$(curl -s http://localhost:5000/)
          echo "Server response: $response"
          if [[ "$response" == *'Hello WSB! Greetings from Flask!'* ]]; then
            echo "Response test passed"
          else
            echo "Response test failed"
            exit 1


